### ISSUE TITLE
Linter issue

### ISSUE THREAD

**Issue by graciemcguire** [learn-co-curriculum/phase-0-canvas-lesson-types#1]
### Canvas Link

https://learning.flatironschool.com/courses/3280/pages/lesson-types?module_item_id=142625

### Concern

`has-learning-goals: Missing ## Learning Goals heading [Add a ## Learning Goals section]`

**Comment by ihollander** [comment]
Learning goals aren't really applicable here since this is just a reference lesson, so we can ignore the linter on this one.
